### ISSUE TITLE
NestedScrollViewPage滑动问题

### ISSUE THREAD

**Issue by qq329401134** [xuelongqy/flutter_easy_refresh#122]
1.将NestedScrollViewPage的List数量调整到100
2.将列表拖到大概第30条的样子
3.然后快速下拉一次，让他自己往下滚动
4.未到第一个list，appbar就展开了
但是慢慢的下拉就不会出现这个问题，是什么原因呢

**Comment by xuelongqy** [comment]
NestedScrollView不是太友好本身有一些问题，不建议使用。可以使用EasyRefresh.custom或CustomScrollView+AppBar的方式

**Comment by qq329401134** [comment]
> NestedScrollView不是太友好本身有一些问题，不建议使用。可以使用EasyRefresh.custom或CustomScrollView+AppBar的方式

因为我是有个tabbarview，请问下如何用CustomScrollView实现呢，就是小红书主页的那种

**Comment by qq329401134** [comment]
> NestedScrollView不是太友好本身有一些问题，不建议使用。可以使用EasyRefresh.custom或CustomScrollView+AppBar的方式

那请问下如何用easyrefresh来包裹一个tabbarview呢就是让整个tabbarview下拉

**Comment by xuelongqy** [comment]
TabView的话，我建议不要使用折叠头部，目前还没有一个很好的解决方案

**Comment by charmfocus** [comment]
这个问题是很难处理，我这也尝试了各种办法，都没有实现 easyrefresh里包裹tabbarview，最接近的一个方案就是NestedScrollView中header里放tabbar,body里放tabbarview，实现整体布局，easyrefresh.builder包裹了NestedScrollView后没有下拉刷新效果，实在很郁闷

**Comment by xuelongqy** [comment]
> 这个问题是很难处理，我这也尝试了各种办法，都没有实现 easyrefresh里包裹tabbarview，最接近的一个方案就是NestedScrollView中header里放tabbar,body里放tabbarview，实现整体布局，easyrefresh.builder包裹了NestedScrollView后没有下拉刷新效果，实在很郁闷

是的，目前没有很好的解决方案。NestedScrollView的设计上来看，就不能很好的使用刷新组件。建议使用示例中的NestedScrollView使用方法，虽然有瑕疵，但是并不影响使用

**Comment by charmfocus** [comment]
@xuelongqy 一位网友hack了NestedScrollView，他示例里有实现这样的效果，但他给的下拉刷新样式太单一，不知道咱们能否结合到easyrefresh中，替换他给的NestedScrollViewRefreshIndicator

**Comment by xuelongqy** [comment]
> @xuelongqy 一位网友hack了[NestedScrollView](https://github.com/fluttercandies/extended_nested_scroll_view)，
> 他示例里有实现这样的效果，但他给的下拉刷新样式太单一，不知道咱们能否结合到easyrefresh中，替换他给的NestedScrollViewRefreshIndicator

可能没有办法，原理不同

**Comment by 972223177** [comment]
老大哥解决了不。实在郁闷

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;
