### ISSUE TITLE
把首次刷新的 demo , slivers 改成 SliverGrid 时 Footer 刚进入时没有自动隐藏

### ISSUE THREAD

**Issue by InsectQY** [xuelongqy/flutter_easy_refresh#195]
![图片](https://user-images.githubusercontent.com/22448409/69490198-2aedee80-0ebf-11ea-9bcc-c9858c63879a.jpeg)
``` dart
slivers: <Widget>[
          // SliverList(
          //   delegate: SliverChildBuilderDelegate(
          //     (context, index) {
          //       return SampleListItem();
          //     },
          //     childCount: _count,
          //   ),
          // ),
          SliverGrid(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                childAspectRatio: 0.6
),
            delegate: SliverChildBuilderDelegate((context, index) {
              return SampleListItem();
            }, childCount: _count),
          ),
        ],
```

**Comment by xuelongqy** [comment]
这个原因未知，等下一次flutter版本更新看效果吧。解决方案，可以更具首次刷新之前数据是否为空，去隐藏SliverGrid，或者设置onLoad

**Comment by xuelongqy** [comment]
提供一个解决方案
```dart
          if (_count > 0) SliverGrid(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                childAspectRatio: 0.6
            ),
            delegate: SliverChildBuilderDelegate((context, index) {
              return Card();
            }, childCount: _count),
          ),
```

**Comment by songbai1211** [comment]
这个问题坑死我了。。。。。

**Comment by lan2000** [comment]
flutter_easyrefresh 2.2.1  
当slivers里的SliverList换成SliverGrid后，firstRefresh功能就失效了
我也出现这个问题了

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
    ! Device emulator-5556 is offline.

• No issues found!
```

**Comment by lan2000** [comment]
> 提供一个解决方案
> 
> ```dart
>           if (_count > 0) SliverGrid(
>             gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
>                 crossAxisCount: 2,
>                 childAspectRatio: 0.6
>             ),
>             delegate: SliverChildBuilderDelegate((context, index) {
>               return Card();
>             }, childCount: _count),
>           ),
> ```

感谢提供的解决方案！

**Comment by lan2000** [comment]
> 提供一个解决方案
> 
> ```dart
>           if (_count > 0) SliverGrid(
>             gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
>                 crossAxisCount: 2,
>                 childAspectRatio: 0.6
>             ),
>             delegate: SliverChildBuilderDelegate((context, index) {
>               return Card();
>             }, childCount: _count),
>           ),
> ```

感谢xuelongqy提供的解决方案

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
