### ISSUE TITLE
当设置Scaffold的extendBodyBehindAppBar属性为true时，AppBar会遮盖下拉刷新组件

### ISSUE THREAD

**Issue by swufexlm** [xuelongqy/flutter_easy_refresh#291]
当设置Scaffold的extendBodyBehindAppBar属性为true时，AppBar会遮盖下拉刷新组件，请问这种情况该如何处理？
我尝试过在EasyRefresh.custom的slivers数组中添加一个和AppBar等高的空白sliver，然后设置headerIndex为1，最终的slivers为[空白，header，body]，但是这样就无法触发下拉刷新了。

**Comment by medz** [comment]
再告诉你一个 Bug，设置 extendBody = true 你会发现底部加载组建被 bottomAppBar 覆盖

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开

**Comment by 944095635** [comment]
还是有问题，listview 下来刷新的距离变得非常长，

**Comment by 944095635** [comment]
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/12290819/4a34f70c-05e2-4124-8361-efc33590b712)

**Comment by xuelongqy** [comment]
> ![image](https://user-images.githubusercontent.com/12290819/264251159-4a34f70c-05e2-4124-8361-efc33590b712.png)

这个看起来是安全区域的问题，将Header的safeArea设置为false，试试呢
