### ISSUE TITLE
使用CustomScrollView的center属性时刷新组件会报错

### ISSUE THREAD

**Issue by w497763094** [xuelongqy/flutter_easy_refresh#296]
报错内容是：'package:flutter_easyrefresh/src/header/refresh_indicator.dart': Failed assertion: line 189 pos 12: 'constraints.growthDirection == GrowthDirection.forward': is not true.
我把这行注释掉之后会报：SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
