### ISSUE TITLE
和scrollable_positioned_list配合使用

### ISSUE THREAD

**Issue by gaoyong06** [xuelongqy/flutter_easy_refresh#317]
因为要监听当前滑动的item,所以使用了scrollable_positioned_list
然后做了如下的嵌套：

`

    EasyRefresh.custom(
        enableControlFinishLoad: true,
        controller: _controller,
        footer: ListHelper.getClassicalFooter(context),
        slivers: <Widget>[
          
          ScrollablePositionedList.separated(
            itemCount: convertInt(_feedList?.length),
            itemBuilder: (context, itemIndex) => itemBuilder(context, itemIndex),
            itemScrollController: itemScrollController,
            itemPositionsListener: itemPositionsListener, 
            separatorBuilder: (BuildContext context, int itemIndex) { 
              return FeedHelper.separatorAdBuilder(context, itemIndex);
             },
          )
        ],
    
        //关闭下拉刷新
        onRefresh: null,
        onLoad: _onLoading,
        emptyWidget: _feedList.length > 0
            ? null
            : EmptyWidget(
              isShowImg: false,
                content: userFeedIsEmptyMessage,
              ),
      ),
      
`

但是一直在报错，错误信息如下：

`

    I/flutter (14262): 
    I/flutter (14262): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
    I/flutter (14262): The following assertion was thrown:
    I/flutter (14262): A RenderViewport expected a child of type RenderSliver but received a child of type
    I/flutter (14262): RenderPointerListener.
    I/flutter (14262): RenderObjects expect specific types of children because they coordinate with their children during
    I/flutter (14262): layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
    I/flutter (14262): RenderSliver does not understand the RenderBox layout protocol.
    I/flutter (14262): 
    I/flutter (14262): The RenderViewport that expected a RenderSliver child was created by:
    I/flutter (14262):   Viewport ← IgnorePointer-[GlobalKey#418ab] ← Semantics ← _PointerListener ← Listener ←
    I/flutter (14262):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#eb0ff] ←
    I/flutter (14262):   _PointerListener ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#bb115] ←
    I/flutter (14262):   RepaintBoundary ← ⋯
    I/flutter (14262): 
    I/flutter (14262): The RenderPointerListener that did not match the expected child type was created by:
    I/flutter (14262):   _PointerListener ← Listener ← RawGestureDetector ← GestureDetector ← ScrollablePositionedList ←
    I/flutter (14262):   Viewport ← IgnorePointer-[GlobalKey#418ab] ← Semantics ← _PointerListener ← Listener ←
    I/flutter (14262):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#eb0ff] ← ⋯
    I/flutter (14262): 
    I/flutter (14262): When the exception was thrown, this was the stack:
    I/flutter (14262): #0      ContainerRenderObjectMixin.debugValidateChild.<anonymous closure> (package:flutter/src/rendering/object.dart:3062:9)
    I/flutter (14262): #1      ContainerRenderObjectMixin.debugValidateChild (package:flutter/src/rendering/object.dart:3089:6)
    I/flutter (14262): #2      MultiChildRenderObjectElement.insertChildRenderObject (package:flutter/src/widgets/framework.dart:5902:25)
    I/flutter (14262): #3      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5679:35)
    I/flutter (14262): #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5376:5)
    I/flutter (14262): #5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5829:11)
    I/flutter (14262): ...     Normal element mounting (29 frames)
    I/flutter (14262): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    I/flutter (14262): #35     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
    I/flutter (14262): #36     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:196:11)
    I/flutter (14262): ...     Normal element mounting (110 frames)
    I/flutter (14262): #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    I/flutter (14262): #147    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
    I/flutter (14262): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
    I/flutter (14262): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
    I/flutter (14262): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
    I/flutter (14262): #151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
    I/flutter (14262): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
    I/flutter (14262): #153    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
    I/flutter (14262): #154    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
    I/flutter (14262): #155    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
    I/flutter (14262): #156    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
    I/flutter (14262): #157    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
    I/flutter (14262): #158    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
    I/flutter (14262): #162    _invoke (dart:ui/hooks.dart:261:10)
    I/flutter (14262): #163    _drawFrame (dart:ui/hooks.dart:219:3)
    I/flutter (14262): (elided 3 frames from dart:async)
    I/flutter (14262): ════════════════════════════════════════════════════════════════════════════════════════════════════
    I/flutter (14262): Another exception was thrown: A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.

      
`

下面是scrollable_positioned_list：
[scrollable_positioned_list](https://pub.flutter-io.cn/packages/scrollable_positioned_list#-readme-tab-)

**Comment by xuelongqy** [comment]
目前不支持

**Comment by gaoyong06** [comment]
> 目前不支持

收到，感谢回复

**Comment by xuelongqy** [comment]
可以使用EasyRefresh.builder，然后修改scrollable_positioned_list源码，通过传参方式把header和footer，设置到PositionedList中(同CustomScrollView)

**Comment by yuanzhiying** [comment]
你好问下，现在可以吗？

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
