### ISSUE TITLE
里面套ListView配合shrinkWrap 和physics会出现奇怪的现象

### ISSUE THREAD

**Issue by pslxx** [xuelongqy/flutter_easy_refresh#335]
![image](https://user-images.githubusercontent.com/8417207/88030629-10633680-cb6e-11ea-8272-bdf48a9d808c.png)

![1595319734104797](https://user-images.githubusercontent.com/8417207/88031004-8f586f00-cb6e-11ea-853b-730f272bd3e7.gif)

**Comment by xuelongqy** [comment]
目前不支持设置这两个属性

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
