### ISSUE TITLE
iPhone模拟器如何显示中文

### ISSUE THREAD

**Issue by NieYinlong** [xuelongqy/flutter_easy_refresh#342]
请问下 iPhone模拟器如何显示中文

**Comment by SeeYouWilsen** [comment]
Setting-General-Luanguage&Region-IPhone Language-简体中文

**Comment by NieYinlong** [comment]
模拟器已经设置了中文, 但是刷新控件还是显示英文

**Comment by NieYinlong** [comment]
模拟器已经设置了中文, 但是刷新控件还是显示英文


![image](https://user-images.githubusercontent.com/15773477/90380789-1685fd80-e0af-11ea-9a3c-a8b8a9cb069c.png)

![image](https://user-images.githubusercontent.com/15773477/90380843-2d2c5480-e0af-11ea-9c1a-c79dd3af3409.png)

**Comment by genius1212** [comment]
去看下flutter国际化，
localizationsDelegates: [
            GlobalEasyRefreshLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            const FallbackCupertinoLocalisationsDelegate(),
          ],
