### ISSUE TITLE
下拉刷新自动刷新

### ISSUE THREAD

**Issue by zhouxianjun** [xuelongqy/flutter_easy_refresh#348]
请问如何在下拉达到触发刷新高度时自动触发刷新，我看源码里面773行判断了_focus为false则触发刷新。我想要达到下拉高度后，不管是否在滚动都直接触发刷新。

**Comment by xuelongqy** [comment]
后面版本会通过参数的方式增加此功能

**Comment by xuelongqy** [comment]
v3.0.2 Indicator添加triggerWhenReach参数
