### ISSUE TITLE
在extended.NestedScrollView下 使用了控制器后自定义 firstRefreshWidget 无效 调用 finishRefresh 无效  topBouncing false 无效

### ISSUE THREAD

**Issue by tom0gao** [xuelongqy/flutter_easy_refresh#349]
代码层级 extended.NestedScrollViewRefreshIndicator(
child : extended.NestedScrollView(body:extended.NestedScrollViewInnerScrollPositionKeyWidget('key',EasyRefresh())) ,
)

**Comment by xuelongqy** [comment]
请参考示例

**Comment by tom0gao** [comment]
问题都出自使用 extended.NestedScrollViewRefreshIndicator 后

**Comment by tom0gao** [comment]
代码层级 extended.NestedScrollViewRefreshIndicator(
  child : extended.NestedScrollView(body:extended.NestedScrollViewInnerScrollPositionKeyWidget('key',EasyRefresh())) ,
)

**Comment by xuelongqy** [comment]
NestedScrollview可能会出现兼容问题。topBouncing在文档中有说明[api文档](https://pub.dev/documentation/flutter_easyrefresh/latest/easyrefresh/EasyRefresh-class.html)

**Comment by tom0gao** [comment]
出现奇怪的原因是因为 child 用了 GridView

**Comment by xuelongqy** [comment]
NestedScrollViewRefreshIndicator？？这是另一个刷新组件吧，混用不会出问题吗？

**Comment by tom0gao** [comment]
@xuelongqy 在NestedScrollview下使用flutter_easyrefresh的子集不要是表格布局就没什么问题了
用了这个NestedScrollViewRefreshIndicator后把easyrefresh的刷新关掉就好了 如果使用easyrefresh自带的刷新 偶尔出现莫名的弹跳现象 目前把表格布局使用listview.build中的item分成两栏解决了那个奇怪的问题

**Comment by xuelongqy** [comment]
> @xuelongqy 在NestedScrollview下使用flutter_easyrefresh的子集不要是表格布局就没什么问题了
> 用了这个NestedScrollViewRefreshIndicator后把easyrefresh的刷新关掉就好了 如果使用easyrefresh自带的刷新 偶尔出现莫名的弹跳现象 目前把表格布局使用listview.build中的item分成两栏解决了那个奇怪的问题

好的，非常感谢。此issue在未解决之前会一直保留

**Comment by quanke** [comment]
这个问题我也遇到了

**Comment by smallbad** [comment]
如何关闭上拉时的越界回弹效果呢

**Comment by tom0gao** [comment]
@smallbad topBouncing你指的这个参数吗？

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
