### ISSUE TITLE
当未滑动到底部时，是否支持给定一个距离预加载更多。

### ISSUE THREAD

**Issue by wanderingGuy** [xuelongqy/flutter_easy_refresh#379]
之所以提这个问题，是因为发现一个尴尬的问题：
当设置 footer 的 enableInfiniteLoad 为 true 时，如果加载更多请求失败，footer 不会消失，且不能直接再次上拉加载更多，这个交互有点奇怪。

而当 enableInfiniteLoad 设置为 false 时就没这个问题了，但新的问题是每次需要上拉到足够 triggerDistance 才能触发加载更多，这个体验在长列表下，显然没有 ”当滑到底就加载更多“ 体验好。

不知道我是否描述清楚了问题，望大佬回复。

**Comment by Tinaltt** [comment]
遇到了同样的问题，本想着通过scrollController 自定义实现一下，发现scrollController 添加的listener根本不触发。

**Comment by xuelongqy** [comment]
v3已支持，请及时更新
