### ISSUE TITLE
2.1.6 onRefersh 清除数据源之后触发刷新报错

### ISSUE THREAD

**Issue by zzy080615** [xuelongqy/flutter_easy_refresh#382]
The following assertion was thrown while dispatching notifications for ValueNotifier<TaskState>:
flutter: setState() called after dispose(): _EasyRefreshSliverLoadControlState

解决方案在import 'header/refresh_indicator.dart';
在633行修改为
          if (mounted)setState(() {});
应该是作者笔误  麻烦下个版本修复

**Comment by xuelongqy** [comment]
非常感谢，将在下个版本修复

**Comment by ymwm-lxl** [comment]
我使用的2.1.8还是存在这样的问题，盼处理

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
