### ISSUE TITLE
上拉或者下拉加载的时候，有的时候header和footer没有显示

### ISSUE THREAD

**Issue by jiyunkeji** [xuelongqy/flutter_easy_refresh#385]
enableInfiniteLoad: true,这种情况
如图：我在BasicPage例子里面也出现这样的问题。这个现象好像是我在最上面，直接一滑就滑到底，就没显示了。
![1401604382312_ pic](https://user-images.githubusercontent.com/50569560/97953340-1f978880-1ddb-11eb-8bcb-722ee356c4a9.jpg)

只要往回一点，重新上拉就可以加载了。

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
