### ISSUE TITLE
多次刷新时，当第一次刷新未结束，后面的刷新直接被忽略了

### ISSUE THREAD

**Issue by fuyunmanbu** [xuelongqy/flutter_easy_refresh#406]
多个标签按钮，快速调用callRefresh方法时，后面的刷新直接被忽略了

**Comment by xuelongqy** [comment]
什么样的需求需要同时多次刷新？任务没结束前，不会在触发

**Comment by fuyunmanbu** [comment]
还真有这种需求，比如用按钮控制列表刷新，当有多个按钮时，来回切换，后面的直接被忽略了。

**Comment by xuelongqy** [comment]
请使用TabBarView类似方案实现

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
