### ISSUE TITLE
如代码所示,不能正确地刷新和加载

### ISSUE THREAD

**Issue by hu70258tao** [xuelongqy/flutter_easy_refresh#409]
class _State extends State<TestPage>{
  List<String> datas = ["胡","许","唐"];
  Widget child(String text){
    return Text(text,style:const TextStyle(fontSize: 50),key: ValueKey(text));
  }
  @override
  Widget build(BuildContext context) {
    List<Widget> children = [];
    for(String data in datas){
      children.add(child(data));
    }
    ListView listView= ListView(
      children: children,
    );
    ReorderableListView list =  ReorderableListView(
      onReorder: (int oldIndex, int newIndex){},
      children: children,
    );
    Container container = Container(
      height: MediaQuery.of(context).size.height,
      child: list,
    );
    EasyRefresh easyRefresh =  EasyRefresh(
      child: container,
      onRefresh: () async{
        setState(() {
          datas = ["胡","许","唐"];
        });
      },
      onLoad: () async {
        setState(() {
          datas = ["胡","许","唐","赵","钱","孙","李","王","张","曹","刘","马","吕","典","甘","荀"];
        });
      },
    );
    return Scaffold(
      appBar: AppBar(),
      body: easyRefresh,
    );
  }
}

**Comment by hu70258tao** [comment]
datas的内容较少,没有产生滚动的时候,刷新和加载都正常,
但是当datas较多产生滚动时,刷新和加载都不会再触发

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
